### ISSUE TITLE
Config test fails with --watch

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#271]
When running `npm run test:unit -- --watch` sometimes config file starts to fail.
Restarting test process fixes that (for a while).

```
 1) The config helper conf.get method when EXAMPLE_CONFIG_KEY is "http://defaults.com" in the defaults file should return "http://defaults.com":

      Error: Expected 'undefined' to equal 'http://defaults.com'
      + expected - actual

      -undefined
      +http://defaults.com
      
      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toEqual (node_modules/expect/lib/Expectation.js:81:30)
      at Context.<anonymous> (test/unit/src/server/helpers/t_config.js:23:56)
```

---

Copied from Trello card: https://trello.com/c/NpRuwl8W/252-config-test-fails-with-watch
Labels:

**Comment by katiefenn** [comment]
K: 3,
B: 3,
C: 3

**Comment by solazio** [comment]
Not relevant anymore for snapcraft.io, closing
